// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: event.proto

//go:build !protoopaque

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BettingStatus int32

const (
	BettingStatus_BettingUnknown   BettingStatus = 0
	BettingStatus_BettingOpen      BettingStatus = 1
	BettingStatus_BettingSuspended BettingStatus = 2
	BettingStatus_BettingClosed    BettingStatus = 3
)

// Enum value maps for BettingStatus.
var (
	BettingStatus_name = map[int32]string{
		0: "BettingUnknown",
		1: "BettingOpen",
		2: "BettingSuspended",
		3: "BettingClosed",
	}
	BettingStatus_value = map[string]int32{
		"BettingUnknown":   0,
		"BettingOpen":      1,
		"BettingSuspended": 2,
		"BettingClosed":    3,
	}
)

func (x BettingStatus) Enum() *BettingStatus {
	p := new(BettingStatus)
	*p = x
	return p
}

func (x BettingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BettingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_event_proto_enumTypes[0].Descriptor()
}

func (BettingStatus) Type() protoreflect.EnumType {
	return &file_event_proto_enumTypes[0]
}

func (x BettingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// RaceStatus tracks the lifecycle of the race itself, which is separate from
// whether betting is open on it.
type RaceStatus int32

const (
	RaceStatus_RaceUnknown   RaceStatus = 0
	RaceStatus_RaceScheduled RaceStatus = 1
	RaceStatus_RaceRunning   RaceStatus = 2
	RaceStatus_RaceInterim   RaceStatus = 3
	RaceStatus_RaceFinal     RaceStatus = 4
	RaceStatus_RaceAbandoned RaceStatus = 5
)

// Enum value maps for RaceStatus.
var (
	RaceStatus_name = map[int32]string{
		0: "RaceUnknown",
		1: "RaceScheduled",
		2: "RaceRunning",
		3: "RaceInterim",
		4: "RaceFinal",
		5: "RaceAbandoned",
	}
	RaceStatus_value = map[string]int32{
		"RaceUnknown":   0,
		"RaceScheduled": 1,
		"RaceRunning":   2,
		"RaceInterim":   3,
		"RaceFinal":     4,
		"RaceAbandoned": 5,
	}
)

func (x RaceStatus) Enum() *RaceStatus {
	p := new(RaceStatus)
	*p = x
	return p
}

func (x RaceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RaceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_event_proto_enumTypes[1].Descriptor()
}

func (RaceStatus) Type() protoreflect.EnumType {
	return &file_event_proto_enumTypes[1]
}

func (x RaceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type OptionalBettingStatus struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Value         BettingStatus          `protobuf:"varint,1,opt,name=Value,proto3,enum=model.BettingStatus" json:"Value,omitempty"`
	Deleted       bool                   `protobuf:"varint,2,opt,name=Deleted,proto3" json:"Deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionalBettingStatus) Reset() {
	*x = OptionalBettingStatus{}
	mi := &file_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionalBettingStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalBettingStatus) ProtoMessage() {}

func (x *OptionalBettingStatus) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OptionalBettingStatus) GetValue() BettingStatus {
	if x != nil {
		return x.Value
	}
	return BettingStatus_BettingUnknown
}

func (x *OptionalBettingStatus) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *OptionalBettingStatus) SetValue(v BettingStatus) {
	x.Value = v
}

func (x *OptionalBettingStatus) SetDeleted(v bool) {
	x.Deleted = v
}

type OptionalBettingStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Value   BettingStatus
	Deleted bool
}

func (b0 OptionalBettingStatus_builder) Build() *OptionalBettingStatus {
	m0 := &OptionalBettingStatus{}
	b, x := &b0, m0
	_, _ = b, x
	x.Value = b.Value
	x.Deleted = b.Deleted
	return m0
}

type OptionalRaceStatus struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Value         RaceStatus             `protobuf:"varint,1,opt,name=Value,proto3,enum=model.RaceStatus" json:"Value,omitempty"`
	Deleted       bool                   `protobuf:"varint,2,opt,name=Deleted,proto3" json:"Deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionalRaceStatus) Reset() {
	*x = OptionalRaceStatus{}
	mi := &file_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionalRaceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalRaceStatus) ProtoMessage() {}

func (x *OptionalRaceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OptionalRaceStatus) GetValue() RaceStatus {
	if x != nil {
		return x.Value
	}
	return RaceStatus_RaceUnknown
}

func (x *OptionalRaceStatus) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *OptionalRaceStatus) SetValue(v RaceStatus) {
	x.Value = v
}

func (x *OptionalRaceStatus) SetDeleted(v bool) {
	x.Deleted = v
}

type OptionalRaceStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Value   RaceStatus
	Deleted bool
}

func (b0 OptionalRaceStatus_builder) Build() *OptionalRaceStatus {
	m0 := &OptionalRaceStatus{}
	b, x := &b0, m0
	_, _ = b, x
	x.Value = b.Value
	x.Deleted = b.Deleted
	return m0
}

// Event models a betting match/race
type Event struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name          *OptionalString        `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	StartTime     *OptionalInt64         `protobuf:"bytes,3,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	BettingStatus *OptionalBettingStatus `protobuf:"bytes,4,opt,name=BettingStatus,proto3" json:"BettingStatus,omitempty"`
	Markets       []*Market              `protobuf:"bytes,5,rep,name=Markets,proto3" json:"Markets,omitempty"`
	EventTypeID   *OptionalString        `protobuf:"bytes,6,opt,name=EventTypeID,proto3" json:"EventTypeID,omitempty"`
	SportData     *SportEvent            `protobuf:"bytes,7,opt,name=SportData,proto3" json:"SportData,omitempty"`
	// Whether the Event should be displayed. Unset is treated as hidden.
	Display       *OptionalBool `protobuf:"bytes,8,opt,name=Display,proto3" json:"Display,omitempty"`
	RacingData    *RacingEvent  `protobuf:"bytes,9,opt,name=RacingData,proto3" json:"RacingData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Event) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Event) GetName() *OptionalString {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *Event) GetStartTime() *OptionalInt64 {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Event) GetBettingStatus() *OptionalBettingStatus {
	if x != nil {
		return x.BettingStatus
	}
	return nil
}

func (x *Event) GetMarkets() []*Market {
	if x != nil {
		return x.Markets
	}
	return nil
}

func (x *Event) GetEventTypeID() *OptionalString {
	if x != nil {
		return x.EventTypeID
	}
	return nil
}

func (x *Event) GetSportData() *SportEvent {
	if x != nil {
		return x.SportData
	}
	return nil
}

func (x *Event) GetDisplay() *OptionalBool {
	if x != nil {
		return x.Display
	}
	return nil
}

func (x *Event) GetRacingData() *RacingEvent {
	if x != nil {
		return x.RacingData
	}
	return nil
}

func (x *Event) SetID(v string) {
	x.ID = v
}

func (x *Event) SetName(v *OptionalString) {
	x.Name = v
}

func (x *Event) SetStartTime(v *OptionalInt64) {
	x.StartTime = v
}

func (x *Event) SetBettingStatus(v *OptionalBettingStatus) {
	x.BettingStatus = v
}

func (x *Event) SetMarkets(v []*Market) {
	x.Markets = v
}

func (x *Event) SetEventTypeID(v *OptionalString) {
	x.EventTypeID = v
}

func (x *Event) SetSportData(v *SportEvent) {
	x.SportData = v
}

func (x *Event) SetDisplay(v *OptionalBool) {
	x.Display = v
}

func (x *Event) SetRacingData(v *RacingEvent) {
	x.RacingData = v
}

func (x *Event) HasName() bool {
	if x == nil {
		return false
	}
	return x.Name != nil
}

func (x *Event) HasStartTime() bool {
	if x == nil {
		return false
	}
	return x.StartTime != nil
}

func (x *Event) HasBettingStatus() bool {
	if x == nil {
		return false
	}
	return x.BettingStatus != nil
}

func (x *Event) HasEventTypeID() bool {
	if x == nil {
		return false
	}
	return x.EventTypeID != nil
}

func (x *Event) HasSportData() bool {
	if x == nil {
		return false
	}
	return x.SportData != nil
}

func (x *Event) HasDisplay() bool {
	if x == nil {
		return false
	}
	return x.Display != nil
}

func (x *Event) HasRacingData() bool {
	if x == nil {
		return false
	}
	return x.RacingData != nil
}

func (x *Event) ClearName() {
	x.Name = nil
}

func (x *Event) ClearStartTime() {
	x.StartTime = nil
}

func (x *Event) ClearBettingStatus() {
	x.BettingStatus = nil
}

func (x *Event) ClearEventTypeID() {
	x.EventTypeID = nil
}

func (x *Event) ClearSportData() {
	x.SportData = nil
}

func (x *Event) ClearDisplay() {
	x.Display = nil
}

func (x *Event) ClearRacingData() {
	x.RacingData = nil
}

type Event_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ID            string
	Name          *OptionalString
	StartTime     *OptionalInt64
	BettingStatus *OptionalBettingStatus
	Markets       []*Market
	EventTypeID   *OptionalString
	SportData     *SportEvent
	// Whether the Event should be displayed. Unset is treated as hidden.
	Display    *OptionalBool
	RacingData *RacingEvent
}

func (b0 Event_builder) Build() *Event {
	m0 := &Event{}
	b, x := &b0, m0
	_, _ = b, x
	x.ID = b.ID
	x.Name = b.Name
	x.StartTime = b.StartTime
	x.BettingStatus = b.BettingStatus
	x.Markets = b.Markets
	x.EventTypeID = b.EventTypeID
	x.SportData = b.SportData
	x.Display = b.Display
	x.RacingData = b.RacingData
	return m0
}

// SportEvent models event details that are specific to sports
type SportEvent struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Name          *OptionalString        `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Region        *OptionalString        `protobuf:"bytes,2,opt,name=Region,proto3" json:"Region,omitempty"`
	League        *OptionalString        `protobuf:"bytes,3,opt,name=League,proto3" json:"League,omitempty"`
	Round         *OptionalString        `protobuf:"bytes,4,opt,name=Round,proto3" json:"Round,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SportEvent) Reset() {
	*x = SportEvent{}
	mi := &file_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SportEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SportEvent) ProtoMessage() {}

func (x *SportEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SportEvent) GetName() *OptionalString {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *SportEvent) GetRegion() *OptionalString {
	if x != nil {
		return x.Region
	}
	return nil
}

func (x *SportEvent) GetLeague() *OptionalString {
	if x != nil {
		return x.League
	}
	return nil
}

func (x *SportEvent) GetRound() *OptionalString {
	if x != nil {
		return x.Round
	}
	return nil
}

func (x *SportEvent) SetName(v *OptionalString) {
	x.Name = v
}

func (x *SportEvent) SetRegion(v *OptionalString) {
	x.Region = v
}

func (x *SportEvent) SetLeague(v *OptionalString) {
	x.League = v
}

func (x *SportEvent) SetRound(v *OptionalString) {
	x.Round = v
}

func (x *SportEvent) HasName() bool {
	if x == nil {
		return false
	}
	return x.Name != nil
}

func (x *SportEvent) HasRegion() bool {
	if x == nil {
		return false
	}
	return x.Region != nil
}

func (x *SportEvent) HasLeague() bool {
	if x == nil {
		return false
	}
	return x.League != nil
}

func (x *SportEvent) HasRound() bool {
	if x == nil {
		return false
	}
	return x.Round != nil
}

func (x *SportEvent) ClearName() {
	x.Name = nil
}

func (x *SportEvent) ClearRegion() {
	x.Region = nil
}

func (x *SportEvent) ClearLeague() {
	x.League = nil
}

func (x *SportEvent) ClearRound() {
	x.Round = nil
}

type SportEvent_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name   *OptionalString
	Region *OptionalString
	League *OptionalString
	Round  *OptionalString
}

func (b0 SportEvent_builder) Build() *SportEvent {
	m0 := &SportEvent{}
	b, x := &b0, m0
	_, _ = b, x
	x.Name = b.Name
	x.Region = b.Region
	x.League = b.League
	x.Round = b.Round
	return m0
}

// RacingEvent models event details specific to racing codes (horse, greyhound,
// harness). The racing code itself lives in Event.EventTypeID, matching how
// sport events carry their type.
type RacingEvent struct {
	state          protoimpl.MessageState `protogen:"hybrid.v1"`
	Name           *OptionalString        `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"` // display name of the racing code
	Region         *OptionalString        `protobuf:"bytes,2,opt,name=Region,proto3" json:"Region,omitempty"`
	TrackName      *OptionalString        `protobuf:"bytes,3,opt,name=TrackName,proto3" json:"TrackName,omitempty"`
	RaceNumber     *OptionalInt64         `protobuf:"bytes,4,opt,name=RaceNumber,proto3" json:"RaceNumber,omitempty"` // race N on the day's card
	DistanceMetres *OptionalInt64         `protobuf:"bytes,5,opt,name=DistanceMetres,proto3" json:"DistanceMetres,omitempty"`
	TrackCondition *OptionalString        `protobuf:"bytes,6,opt,name=TrackCondition,proto3" json:"TrackCondition,omitempty"` // e.g. Good 4, Soft 6, Heavy 10
	Weather        *OptionalString        `protobuf:"bytes,7,opt,name=Weather,proto3" json:"Weather,omitempty"`
	RaceClass      *OptionalString        `protobuf:"bytes,8,opt,name=RaceClass,proto3" json:"RaceClass,omitempty"` // e.g. Group 1, Maiden, Grade 5
	RaceStatus     *OptionalRaceStatus    `protobuf:"bytes,9,opt,name=RaceStatus,proto3" json:"RaceStatus,omitempty"`
	FieldSize      *OptionalInt64         `protobuf:"bytes,10,opt,name=FieldSize,proto3" json:"FieldSize,omitempty"` // derived, see racingtransform
	Runners        []*Runner              `protobuf:"bytes,11,rep,name=Runners,proto3" json:"Runners,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RacingEvent) Reset() {
	*x = RacingEvent{}
	mi := &file_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RacingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RacingEvent) ProtoMessage() {}

func (x *RacingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RacingEvent) GetName() *OptionalString {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *RacingEvent) GetRegion() *OptionalString {
	if x != nil {
		return x.Region
	}
	return nil
}

func (x *RacingEvent) GetTrackName() *OptionalString {
	if x != nil {
		return x.TrackName
	}
	return nil
}

func (x *RacingEvent) GetRaceNumber() *OptionalInt64 {
	if x != nil {
		return x.RaceNumber
	}
	return nil
}

func (x *RacingEvent) GetDistanceMetres() *OptionalInt64 {
	if x != nil {
		return x.DistanceMetres
	}
	return nil
}

func (x *RacingEvent) GetTrackCondition() *OptionalString {
	if x != nil {
		return x.TrackCondition
	}
	return nil
}

func (x *RacingEvent) GetWeather() *OptionalString {
	if x != nil {
		return x.Weather
	}
	return nil
}

func (x *RacingEvent) GetRaceClass() *OptionalString {
	if x != nil {
		return x.RaceClass
	}
	return nil
}

func (x *RacingEvent) GetRaceStatus() *OptionalRaceStatus {
	if x != nil {
		return x.RaceStatus
	}
	return nil
}

func (x *RacingEvent) GetFieldSize() *OptionalInt64 {
	if x != nil {
		return x.FieldSize
	}
	return nil
}

func (x *RacingEvent) GetRunners() []*Runner {
	if x != nil {
		return x.Runners
	}
	return nil
}

func (x *RacingEvent) SetName(v *OptionalString) {
	x.Name = v
}

func (x *RacingEvent) SetRegion(v *OptionalString) {
	x.Region = v
}

func (x *RacingEvent) SetTrackName(v *OptionalString) {
	x.TrackName = v
}

func (x *RacingEvent) SetRaceNumber(v *OptionalInt64) {
	x.RaceNumber = v
}

func (x *RacingEvent) SetDistanceMetres(v *OptionalInt64) {
	x.DistanceMetres = v
}

func (x *RacingEvent) SetTrackCondition(v *OptionalString) {
	x.TrackCondition = v
}

func (x *RacingEvent) SetWeather(v *OptionalString) {
	x.Weather = v
}

func (x *RacingEvent) SetRaceClass(v *OptionalString) {
	x.RaceClass = v
}

func (x *RacingEvent) SetRaceStatus(v *OptionalRaceStatus) {
	x.RaceStatus = v
}

func (x *RacingEvent) SetFieldSize(v *OptionalInt64) {
	x.FieldSize = v
}

func (x *RacingEvent) SetRunners(v []*Runner) {
	x.Runners = v
}

func (x *RacingEvent) HasName() bool {
	if x == nil {
		return false
	}
	return x.Name != nil
}

func (x *RacingEvent) HasRegion() bool {
	if x == nil {
		return false
	}
	return x.Region != nil
}

func (x *RacingEvent) HasTrackName() bool {
	if x == nil {
		return false
	}
	return x.TrackName != nil
}

func (x *RacingEvent) HasRaceNumber() bool {
	if x == nil {
		return false
	}
	return x.RaceNumber != nil
}

func (x *RacingEvent) HasDistanceMetres() bool {
	if x == nil {
		return false
	}
	return x.DistanceMetres != nil
}

func (x *RacingEvent) HasTrackCondition() bool {
	if x == nil {
		return false
	}
	return x.TrackCondition != nil
}

func (x *RacingEvent) HasWeather() bool {
	if x == nil {
		return false
	}
	return x.Weather != nil
}

func (x *RacingEvent) HasRaceClass() bool {
	if x == nil {
		return false
	}
	return x.RaceClass != nil
}

func (x *RacingEvent) HasRaceStatus() bool {
	if x == nil {
		return false
	}
	return x.RaceStatus != nil
}

func (x *RacingEvent) HasFieldSize() bool {
	if x == nil {
		return false
	}
	return x.FieldSize != nil
}

func (x *RacingEvent) ClearName() {
	x.Name = nil
}

func (x *RacingEvent) ClearRegion() {
	x.Region = nil
}

func (x *RacingEvent) ClearTrackName() {
	x.TrackName = nil
}

func (x *RacingEvent) ClearRaceNumber() {
	x.RaceNumber = nil
}

func (x *RacingEvent) ClearDistanceMetres() {
	x.DistanceMetres = nil
}

func (x *RacingEvent) ClearTrackCondition() {
	x.TrackCondition = nil
}

func (x *RacingEvent) ClearWeather() {
	x.Weather = nil
}

func (x *RacingEvent) ClearRaceClass() {
	x.RaceClass = nil
}

func (x *RacingEvent) ClearRaceStatus() {
	x.RaceStatus = nil
}

func (x *RacingEvent) ClearFieldSize() {
	x.FieldSize = nil
}

type RacingEvent_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name           *OptionalString
	Region         *OptionalString
	TrackName      *OptionalString
	RaceNumber     *OptionalInt64
	DistanceMetres *OptionalInt64
	TrackCondition *OptionalString
	Weather        *OptionalString
	RaceClass      *OptionalString
	RaceStatus     *OptionalRaceStatus
	FieldSize      *OptionalInt64
	Runners        []*Runner
}

func (b0 RacingEvent_builder) Build() *RacingEvent {
	m0 := &RacingEvent{}
	b, x := &b0, m0
	_, _ = b, x
	x.Name = b.Name
	x.Region = b.Region
	x.TrackName = b.TrackName
	x.RaceNumber = b.RaceNumber
	x.DistanceMetres = b.DistanceMetres
	x.TrackCondition = b.TrackCondition
	x.Weather = b.Weather
	x.RaceClass = b.RaceClass
	x.RaceStatus = b.RaceStatus
	x.FieldSize = b.FieldSize
	x.Runners = b.Runners
	return m0
}

// Runner models a single competitor in a race. Runners are held once per Event
// rather than per Market, because the same runner is bet on across every market
// on the race. Markets reference a Runner by using its ID as the Selection ID.
type Runner struct {
	state          protoimpl.MessageState `protogen:"hybrid.v1"`
	ID             string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Number         *OptionalInt64         `protobuf:"bytes,2,opt,name=Number,proto3" json:"Number,omitempty"` // saddlecloth number, or box for greyhounds
	Name           *OptionalString        `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Barrier        *OptionalInt64         `protobuf:"bytes,4,opt,name=Barrier,proto3" json:"Barrier,omitempty"`
	Weight         *OptionalDouble        `protobuf:"bytes,5,opt,name=Weight,proto3" json:"Weight,omitempty"` // carried weight in kg
	Jockey         *OptionalString        `protobuf:"bytes,6,opt,name=Jockey,proto3" json:"Jockey,omitempty"` // driver for harness, unset for greyhounds
	Trainer        *OptionalString        `protobuf:"bytes,7,opt,name=Trainer,proto3" json:"Trainer,omitempty"`
	Scratched      *OptionalBool          `protobuf:"bytes,8,opt,name=Scratched,proto3" json:"Scratched,omitempty"`
	Silks          *OptionalString        `protobuf:"bytes,9,opt,name=Silks,proto3" json:"Silks,omitempty"`
	FinishPosition *OptionalInt64         `protobuf:"bytes,10,opt,name=FinishPosition,proto3" json:"FinishPosition,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Runner) Reset() {
	*x = Runner{}
	mi := &file_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Runner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Runner) ProtoMessage() {}

func (x *Runner) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Runner) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Runner) GetNumber() *OptionalInt64 {
	if x != nil {
		return x.Number
	}
	return nil
}

func (x *Runner) GetName() *OptionalString {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *Runner) GetBarrier() *OptionalInt64 {
	if x != nil {
		return x.Barrier
	}
	return nil
}

func (x *Runner) GetWeight() *OptionalDouble {
	if x != nil {
		return x.Weight
	}
	return nil
}

func (x *Runner) GetJockey() *OptionalString {
	if x != nil {
		return x.Jockey
	}
	return nil
}

func (x *Runner) GetTrainer() *OptionalString {
	if x != nil {
		return x.Trainer
	}
	return nil
}

func (x *Runner) GetScratched() *OptionalBool {
	if x != nil {
		return x.Scratched
	}
	return nil
}

func (x *Runner) GetSilks() *OptionalString {
	if x != nil {
		return x.Silks
	}
	return nil
}

func (x *Runner) GetFinishPosition() *OptionalInt64 {
	if x != nil {
		return x.FinishPosition
	}
	return nil
}

func (x *Runner) SetID(v string) {
	x.ID = v
}

func (x *Runner) SetNumber(v *OptionalInt64) {
	x.Number = v
}

func (x *Runner) SetName(v *OptionalString) {
	x.Name = v
}

func (x *Runner) SetBarrier(v *OptionalInt64) {
	x.Barrier = v
}

func (x *Runner) SetWeight(v *OptionalDouble) {
	x.Weight = v
}

func (x *Runner) SetJockey(v *OptionalString) {
	x.Jockey = v
}

func (x *Runner) SetTrainer(v *OptionalString) {
	x.Trainer = v
}

func (x *Runner) SetScratched(v *OptionalBool) {
	x.Scratched = v
}

func (x *Runner) SetSilks(v *OptionalString) {
	x.Silks = v
}

func (x *Runner) SetFinishPosition(v *OptionalInt64) {
	x.FinishPosition = v
}

func (x *Runner) HasNumber() bool {
	if x == nil {
		return false
	}
	return x.Number != nil
}

func (x *Runner) HasName() bool {
	if x == nil {
		return false
	}
	return x.Name != nil
}

func (x *Runner) HasBarrier() bool {
	if x == nil {
		return false
	}
	return x.Barrier != nil
}

func (x *Runner) HasWeight() bool {
	if x == nil {
		return false
	}
	return x.Weight != nil
}

func (x *Runner) HasJockey() bool {
	if x == nil {
		return false
	}
	return x.Jockey != nil
}

func (x *Runner) HasTrainer() bool {
	if x == nil {
		return false
	}
	return x.Trainer != nil
}

func (x *Runner) HasScratched() bool {
	if x == nil {
		return false
	}
	return x.Scratched != nil
}

func (x *Runner) HasSilks() bool {
	if x == nil {
		return false
	}
	return x.Silks != nil
}

func (x *Runner) HasFinishPosition() bool {
	if x == nil {
		return false
	}
	return x.FinishPosition != nil
}

func (x *Runner) ClearNumber() {
	x.Number = nil
}

func (x *Runner) ClearName() {
	x.Name = nil
}

func (x *Runner) ClearBarrier() {
	x.Barrier = nil
}

func (x *Runner) ClearWeight() {
	x.Weight = nil
}

func (x *Runner) ClearJockey() {
	x.Jockey = nil
}

func (x *Runner) ClearTrainer() {
	x.Trainer = nil
}

func (x *Runner) ClearScratched() {
	x.Scratched = nil
}

func (x *Runner) ClearSilks() {
	x.Silks = nil
}

func (x *Runner) ClearFinishPosition() {
	x.FinishPosition = nil
}

type Runner_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ID             string
	Number         *OptionalInt64
	Name           *OptionalString
	Barrier        *OptionalInt64
	Weight         *OptionalDouble
	Jockey         *OptionalString
	Trainer        *OptionalString
	Scratched      *OptionalBool
	Silks          *OptionalString
	FinishPosition *OptionalInt64
}

func (b0 Runner_builder) Build() *Runner {
	m0 := &Runner{}
	b, x := &b0, m0
	_, _ = b, x
	x.ID = b.ID
	x.Number = b.Number
	x.Name = b.Name
	x.Barrier = b.Barrier
	x.Weight = b.Weight
	x.Jockey = b.Jockey
	x.Trainer = b.Trainer
	x.Scratched = b.Scratched
	x.Silks = b.Silks
	x.FinishPosition = b.FinishPosition
	return m0
}

// Market models a market of betting options e.g Head to Head or Totals
type Market struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name          *OptionalString        `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	StartTime     *OptionalInt64         `protobuf:"bytes,3,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	BettingStatus *OptionalBettingStatus `protobuf:"bytes,4,opt,name=BettingStatus,proto3" json:"BettingStatus,omitempty"`
	Selections    []*Selection           `protobuf:"bytes,5,rep,name=Selections,proto3" json:"Selections,omitempty"`
	// Epoch nanoseconds (UTC) of the first time this market's BettingStatus
	// became BettingClosed. Set once by MarketCloseTransform and never
	// recomputed, so a reopened and re-closed market keeps its first close.
	ClosedAt      *OptionalInt64 `protobuf:"bytes,6,opt,name=ClosedAt,proto3" json:"ClosedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Market) Reset() {
	*x = Market{}
	mi := &file_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Market) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Market) ProtoMessage() {}

func (x *Market) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Market) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Market) GetName() *OptionalString {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *Market) GetStartTime() *OptionalInt64 {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Market) GetBettingStatus() *OptionalBettingStatus {
	if x != nil {
		return x.BettingStatus
	}
	return nil
}

func (x *Market) GetSelections() []*Selection {
	if x != nil {
		return x.Selections
	}
	return nil
}

func (x *Market) GetClosedAt() *OptionalInt64 {
	if x != nil {
		return x.ClosedAt
	}
	return nil
}

func (x *Market) SetID(v string) {
	x.ID = v
}

func (x *Market) SetName(v *OptionalString) {
	x.Name = v
}

func (x *Market) SetStartTime(v *OptionalInt64) {
	x.StartTime = v
}

func (x *Market) SetBettingStatus(v *OptionalBettingStatus) {
	x.BettingStatus = v
}

func (x *Market) SetSelections(v []*Selection) {
	x.Selections = v
}

func (x *Market) SetClosedAt(v *OptionalInt64) {
	x.ClosedAt = v
}

func (x *Market) HasName() bool {
	if x == nil {
		return false
	}
	return x.Name != nil
}

func (x *Market) HasStartTime() bool {
	if x == nil {
		return false
	}
	return x.StartTime != nil
}

func (x *Market) HasBettingStatus() bool {
	if x == nil {
		return false
	}
	return x.BettingStatus != nil
}

func (x *Market) HasClosedAt() bool {
	if x == nil {
		return false
	}
	return x.ClosedAt != nil
}

func (x *Market) ClearName() {
	x.Name = nil
}

func (x *Market) ClearStartTime() {
	x.StartTime = nil
}

func (x *Market) ClearBettingStatus() {
	x.BettingStatus = nil
}

func (x *Market) ClearClosedAt() {
	x.ClosedAt = nil
}

type Market_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ID            string
	Name          *OptionalString
	StartTime     *OptionalInt64
	BettingStatus *OptionalBettingStatus
	Selections    []*Selection
	// Epoch nanoseconds (UTC) of the first time this market's BettingStatus
	// became BettingClosed. Set once by MarketCloseTransform and never
	// recomputed, so a reopened and re-closed market keeps its first close.
	ClosedAt *OptionalInt64
}

func (b0 Market_builder) Build() *Market {
	m0 := &Market{}
	b, x := &b0, m0
	_, _ = b, x
	x.ID = b.ID
	x.Name = b.Name
	x.StartTime = b.StartTime
	x.BettingStatus = b.BettingStatus
	x.Selections = b.Selections
	x.ClosedAt = b.ClosedAt
	return m0
}

// Selection models a betting options e.g Home Team or Over
type Selection struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name          *OptionalString        `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	BettingStatus *OptionalBettingStatus `protobuf:"bytes,3,opt,name=BettingStatus,proto3" json:"BettingStatus,omitempty"`
	Price         *OptionalDouble        `protobuf:"bytes,4,opt,name=Price,proto3" json:"Price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Selection) Reset() {
	*x = Selection{}
	mi := &file_event_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Selection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Selection) ProtoMessage() {}

func (x *Selection) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Selection) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Selection) GetName() *OptionalString {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *Selection) GetBettingStatus() *OptionalBettingStatus {
	if x != nil {
		return x.BettingStatus
	}
	return nil
}

func (x *Selection) GetPrice() *OptionalDouble {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *Selection) SetID(v string) {
	x.ID = v
}

func (x *Selection) SetName(v *OptionalString) {
	x.Name = v
}

func (x *Selection) SetBettingStatus(v *OptionalBettingStatus) {
	x.BettingStatus = v
}

func (x *Selection) SetPrice(v *OptionalDouble) {
	x.Price = v
}

func (x *Selection) HasName() bool {
	if x == nil {
		return false
	}
	return x.Name != nil
}

func (x *Selection) HasBettingStatus() bool {
	if x == nil {
		return false
	}
	return x.BettingStatus != nil
}

func (x *Selection) HasPrice() bool {
	if x == nil {
		return false
	}
	return x.Price != nil
}

func (x *Selection) ClearName() {
	x.Name = nil
}

func (x *Selection) ClearBettingStatus() {
	x.BettingStatus = nil
}

func (x *Selection) ClearPrice() {
	x.Price = nil
}

type Selection_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ID            string
	Name          *OptionalString
	BettingStatus *OptionalBettingStatus
	Price         *OptionalDouble
}

func (b0 Selection_builder) Build() *Selection {
	m0 := &Selection{}
	b, x := &b0, m0
	_, _ = b, x
	x.ID = b.ID
	x.Name = b.Name
	x.BettingStatus = b.BettingStatus
	x.Price = b.Price
	return m0
}

type OptionalString struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=Value,proto3" json:"Value,omitempty"`
	Deleted       bool                   `protobuf:"varint,2,opt,name=Deleted,proto3" json:"Deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionalString) Reset() {
	*x = OptionalString{}
	mi := &file_event_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionalString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalString) ProtoMessage() {}

func (x *OptionalString) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OptionalString) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *OptionalString) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *OptionalString) SetValue(v string) {
	x.Value = v
}

func (x *OptionalString) SetDeleted(v bool) {
	x.Deleted = v
}

type OptionalString_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Value   string
	Deleted bool
}

func (b0 OptionalString_builder) Build() *OptionalString {
	m0 := &OptionalString{}
	b, x := &b0, m0
	_, _ = b, x
	x.Value = b.Value
	x.Deleted = b.Deleted
	return m0
}

type OptionalDouble struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=Value,proto3" json:"Value,omitempty"`
	Deleted       bool                   `protobuf:"varint,3,opt,name=Deleted,proto3" json:"Deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionalDouble) Reset() {
	*x = OptionalDouble{}
	mi := &file_event_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionalDouble) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalDouble) ProtoMessage() {}

func (x *OptionalDouble) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OptionalDouble) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *OptionalDouble) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *OptionalDouble) SetValue(v float64) {
	x.Value = v
}

func (x *OptionalDouble) SetDeleted(v bool) {
	x.Deleted = v
}

type OptionalDouble_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Value   float64
	Deleted bool
}

func (b0 OptionalDouble_builder) Build() *OptionalDouble {
	m0 := &OptionalDouble{}
	b, x := &b0, m0
	_, _ = b, x
	x.Value = b.Value
	x.Deleted = b.Deleted
	return m0
}

type OptionalInt64 struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=Value,proto3" json:"Value,omitempty"`
	Deleted       bool                   `protobuf:"varint,2,opt,name=Deleted,proto3" json:"Deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionalInt64) Reset() {
	*x = OptionalInt64{}
	mi := &file_event_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionalInt64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalInt64) ProtoMessage() {}

func (x *OptionalInt64) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OptionalInt64) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *OptionalInt64) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *OptionalInt64) SetValue(v int64) {
	x.Value = v
}

func (x *OptionalInt64) SetDeleted(v bool) {
	x.Deleted = v
}

type OptionalInt64_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Value   int64
	Deleted bool
}

func (b0 OptionalInt64_builder) Build() *OptionalInt64 {
	m0 := &OptionalInt64{}
	b, x := &b0, m0
	_, _ = b, x
	x.Value = b.Value
	x.Deleted = b.Deleted
	return m0
}

type OptionalBool struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Value         bool                   `protobuf:"varint,1,opt,name=Value,proto3" json:"Value,omitempty"`
	Deleted       bool                   `protobuf:"varint,2,opt,name=Deleted,proto3" json:"Deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionalBool) Reset() {
	*x = OptionalBool{}
	mi := &file_event_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionalBool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalBool) ProtoMessage() {}

func (x *OptionalBool) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OptionalBool) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

func (x *OptionalBool) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *OptionalBool) SetValue(v bool) {
	x.Value = v
}

func (x *OptionalBool) SetDeleted(v bool) {
	x.Deleted = v
}

type OptionalBool_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Value   bool
	Deleted bool
}

func (b0 OptionalBool_builder) Build() *OptionalBool {
	m0 := &OptionalBool{}
	b, x := &b0, m0
	_, _ = b, x
	x.Value = b.Value
	x.Deleted = b.Deleted
	return m0
}

var File_event_proto protoreflect.FileDescriptor

const file_event_proto_rawDesc = "" +
	"\n" +
	"\vevent.proto\x12\x05model\"]\n" +
	"\x15OptionalBettingStatus\x12*\n" +
	"\x05Value\x18\x01 \x01(\x0e2\x14.model.BettingStatusR\x05Value\x12\x18\n" +
	"\aDeleted\x18\x02 \x01(\bR\aDeleted\"W\n" +
	"\x12OptionalRaceStatus\x12'\n" +
	"\x05Value\x18\x01 \x01(\x0e2\x11.model.RaceStatusR\x05Value\x12\x18\n" +
	"\aDeleted\x18\x02 \x01(\bR\aDeleted\"\xb0\x03\n" +
	"\x05Event\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12)\n" +
	"\x04Name\x18\x02 \x01(\v2\x15.model.OptionalStringR\x04Name\x122\n" +
	"\tStartTime\x18\x03 \x01(\v2\x14.model.OptionalInt64R\tStartTime\x12B\n" +
	"\rBettingStatus\x18\x04 \x01(\v2\x1c.model.OptionalBettingStatusR\rBettingStatus\x12'\n" +
	"\aMarkets\x18\x05 \x03(\v2\r.model.MarketR\aMarkets\x127\n" +
	"\vEventTypeID\x18\x06 \x01(\v2\x15.model.OptionalStringR\vEventTypeID\x12/\n" +
	"\tSportData\x18\a \x01(\v2\x11.model.SportEventR\tSportData\x12-\n" +
	"\aDisplay\x18\b \x01(\v2\x13.model.OptionalBoolR\aDisplay\x122\n" +
	"\n" +
	"RacingData\x18\t \x01(\v2\x12.model.RacingEventR\n" +
	"RacingData\"\xc2\x01\n" +
	"\n" +
	"SportEvent\x12)\n" +
	"\x04Name\x18\x01 \x01(\v2\x15.model.OptionalStringR\x04Name\x12-\n" +
	"\x06Region\x18\x02 \x01(\v2\x15.model.OptionalStringR\x06Region\x12-\n" +
	"\x06League\x18\x03 \x01(\v2\x15.model.OptionalStringR\x06League\x12+\n" +
	"\x05Round\x18\x04 \x01(\v2\x15.model.OptionalStringR\x05Round\"\xcd\x04\n" +
	"\vRacingEvent\x12)\n" +
	"\x04Name\x18\x01 \x01(\v2\x15.model.OptionalStringR\x04Name\x12-\n" +
	"\x06Region\x18\x02 \x01(\v2\x15.model.OptionalStringR\x06Region\x123\n" +
	"\tTrackName\x18\x03 \x01(\v2\x15.model.OptionalStringR\tTrackName\x124\n" +
	"\n" +
	"RaceNumber\x18\x04 \x01(\v2\x14.model.OptionalInt64R\n" +
	"RaceNumber\x12<\n" +
	"\x0eDistanceMetres\x18\x05 \x01(\v2\x14.model.OptionalInt64R\x0eDistanceMetres\x12=\n" +
	"\x0eTrackCondition\x18\x06 \x01(\v2\x15.model.OptionalStringR\x0eTrackCondition\x12/\n" +
	"\aWeather\x18\a \x01(\v2\x15.model.OptionalStringR\aWeather\x123\n" +
	"\tRaceClass\x18\b \x01(\v2\x15.model.OptionalStringR\tRaceClass\x129\n" +
	"\n" +
	"RaceStatus\x18\t \x01(\v2\x19.model.OptionalRaceStatusR\n" +
	"RaceStatus\x122\n" +
	"\tFieldSize\x18\n" +
	" \x01(\v2\x14.model.OptionalInt64R\tFieldSize\x12'\n" +
	"\aRunners\x18\v \x03(\v2\r.model.RunnerR\aRunners\"\xce\x03\n" +
	"\x06Runner\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12,\n" +
	"\x06Number\x18\x02 \x01(\v2\x14.model.OptionalInt64R\x06Number\x12)\n" +
	"\x04Name\x18\x03 \x01(\v2\x15.model.OptionalStringR\x04Name\x12.\n" +
	"\aBarrier\x18\x04 \x01(\v2\x14.model.OptionalInt64R\aBarrier\x12-\n" +
	"\x06Weight\x18\x05 \x01(\v2\x15.model.OptionalDoubleR\x06Weight\x12-\n" +
	"\x06Jockey\x18\x06 \x01(\v2\x15.model.OptionalStringR\x06Jockey\x12/\n" +
	"\aTrainer\x18\a \x01(\v2\x15.model.OptionalStringR\aTrainer\x121\n" +
	"\tScratched\x18\b \x01(\v2\x13.model.OptionalBoolR\tScratched\x12+\n" +
	"\x05Silks\x18\t \x01(\v2\x15.model.OptionalStringR\x05Silks\x12<\n" +
	"\x0eFinishPosition\x18\n" +
	" \x01(\v2\x14.model.OptionalInt64R\x0eFinishPosition\"\x9f\x02\n" +
	"\x06Market\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12)\n" +
	"\x04Name\x18\x02 \x01(\v2\x15.model.OptionalStringR\x04Name\x122\n" +
	"\tStartTime\x18\x03 \x01(\v2\x14.model.OptionalInt64R\tStartTime\x12B\n" +
	"\rBettingStatus\x18\x04 \x01(\v2\x1c.model.OptionalBettingStatusR\rBettingStatus\x120\n" +
	"\n" +
	"Selections\x18\x05 \x03(\v2\x10.model.SelectionR\n" +
	"Selections\x120\n" +
	"\bClosedAt\x18\x06 \x01(\v2\x14.model.OptionalInt64R\bClosedAt\"\xb7\x01\n" +
	"\tSelection\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12)\n" +
	"\x04Name\x18\x02 \x01(\v2\x15.model.OptionalStringR\x04Name\x12B\n" +
	"\rBettingStatus\x18\x03 \x01(\v2\x1c.model.OptionalBettingStatusR\rBettingStatus\x12+\n" +
	"\x05Price\x18\x04 \x01(\v2\x15.model.OptionalDoubleR\x05Price\"@\n" +
	"\x0eOptionalString\x12\x14\n" +
	"\x05Value\x18\x01 \x01(\tR\x05Value\x12\x18\n" +
	"\aDeleted\x18\x02 \x01(\bR\aDeleted\"@\n" +
	"\x0eOptionalDouble\x12\x14\n" +
	"\x05Value\x18\x01 \x01(\x01R\x05Value\x12\x18\n" +
	"\aDeleted\x18\x03 \x01(\bR\aDeleted\"?\n" +
	"\rOptionalInt64\x12\x14\n" +
	"\x05Value\x18\x01 \x01(\x03R\x05Value\x12\x18\n" +
	"\aDeleted\x18\x02 \x01(\bR\aDeleted\">\n" +
	"\fOptionalBool\x12\x14\n" +
	"\x05Value\x18\x01 \x01(\bR\x05Value\x12\x18\n" +
	"\aDeleted\x18\x02 \x01(\bR\aDeleted*]\n" +
	"\rBettingStatus\x12\x12\n" +
	"\x0eBettingUnknown\x10\x00\x12\x0f\n" +
	"\vBettingOpen\x10\x01\x12\x14\n" +
	"\x10BettingSuspended\x10\x02\x12\x11\n" +
	"\rBettingClosed\x10\x03*t\n" +
	"\n" +
	"RaceStatus\x12\x0f\n" +
	"\vRaceUnknown\x10\x00\x12\x11\n" +
	"\rRaceScheduled\x10\x01\x12\x0f\n" +
	"\vRaceRunning\x10\x02\x12\x0f\n" +
	"\vRaceInterim\x10\x03\x12\r\n" +
	"\tRaceFinal\x10\x04\x12\x11\n" +
	"\rRaceAbandoned\x10\x05B;Z9git.neds.sh/technology/pricekinetics/tools/codetest/modelb\x06proto3"

var file_event_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_event_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_event_proto_goTypes = []any{
	(BettingStatus)(0),            // 0: model.BettingStatus
	(RaceStatus)(0),               // 1: model.RaceStatus
	(*OptionalBettingStatus)(nil), // 2: model.OptionalBettingStatus
	(*OptionalRaceStatus)(nil),    // 3: model.OptionalRaceStatus
	(*Event)(nil),                 // 4: model.Event
	(*SportEvent)(nil),            // 5: model.SportEvent
	(*RacingEvent)(nil),           // 6: model.RacingEvent
	(*Runner)(nil),                // 7: model.Runner
	(*Market)(nil),                // 8: model.Market
	(*Selection)(nil),             // 9: model.Selection
	(*OptionalString)(nil),        // 10: model.OptionalString
	(*OptionalDouble)(nil),        // 11: model.OptionalDouble
	(*OptionalInt64)(nil),         // 12: model.OptionalInt64
	(*OptionalBool)(nil),          // 13: model.OptionalBool
}
var file_event_proto_depIdxs = []int32{
	0,  // 0: model.OptionalBettingStatus.Value:type_name -> model.BettingStatus
	1,  // 1: model.OptionalRaceStatus.Value:type_name -> model.RaceStatus
	10, // 2: model.Event.Name:type_name -> model.OptionalString
	12, // 3: model.Event.StartTime:type_name -> model.OptionalInt64
	2,  // 4: model.Event.BettingStatus:type_name -> model.OptionalBettingStatus
	8,  // 5: model.Event.Markets:type_name -> model.Market
	10, // 6: model.Event.EventTypeID:type_name -> model.OptionalString
	5,  // 7: model.Event.SportData:type_name -> model.SportEvent
	13, // 8: model.Event.Display:type_name -> model.OptionalBool
	6,  // 9: model.Event.RacingData:type_name -> model.RacingEvent
	10, // 10: model.SportEvent.Name:type_name -> model.OptionalString
	10, // 11: model.SportEvent.Region:type_name -> model.OptionalString
	10, // 12: model.SportEvent.League:type_name -> model.OptionalString
	10, // 13: model.SportEvent.Round:type_name -> model.OptionalString
	10, // 14: model.RacingEvent.Name:type_name -> model.OptionalString
	10, // 15: model.RacingEvent.Region:type_name -> model.OptionalString
	10, // 16: model.RacingEvent.TrackName:type_name -> model.OptionalString
	12, // 17: model.RacingEvent.RaceNumber:type_name -> model.OptionalInt64
	12, // 18: model.RacingEvent.DistanceMetres:type_name -> model.OptionalInt64
	10, // 19: model.RacingEvent.TrackCondition:type_name -> model.OptionalString
	10, // 20: model.RacingEvent.Weather:type_name -> model.OptionalString
	10, // 21: model.RacingEvent.RaceClass:type_name -> model.OptionalString
	3,  // 22: model.RacingEvent.RaceStatus:type_name -> model.OptionalRaceStatus
	12, // 23: model.RacingEvent.FieldSize:type_name -> model.OptionalInt64
	7,  // 24: model.RacingEvent.Runners:type_name -> model.Runner
	12, // 25: model.Runner.Number:type_name -> model.OptionalInt64
	10, // 26: model.Runner.Name:type_name -> model.OptionalString
	12, // 27: model.Runner.Barrier:type_name -> model.OptionalInt64
	11, // 28: model.Runner.Weight:type_name -> model.OptionalDouble
	10, // 29: model.Runner.Jockey:type_name -> model.OptionalString
	10, // 30: model.Runner.Trainer:type_name -> model.OptionalString
	13, // 31: model.Runner.Scratched:type_name -> model.OptionalBool
	10, // 32: model.Runner.Silks:type_name -> model.OptionalString
	12, // 33: model.Runner.FinishPosition:type_name -> model.OptionalInt64
	10, // 34: model.Market.Name:type_name -> model.OptionalString
	12, // 35: model.Market.StartTime:type_name -> model.OptionalInt64
	2,  // 36: model.Market.BettingStatus:type_name -> model.OptionalBettingStatus
	9,  // 37: model.Market.Selections:type_name -> model.Selection
	12, // 38: model.Market.ClosedAt:type_name -> model.OptionalInt64
	10, // 39: model.Selection.Name:type_name -> model.OptionalString
	2,  // 40: model.Selection.BettingStatus:type_name -> model.OptionalBettingStatus
	11, // 41: model.Selection.Price:type_name -> model.OptionalDouble
	42, // [42:42] is the sub-list for method output_type
	42, // [42:42] is the sub-list for method input_type
	42, // [42:42] is the sub-list for extension type_name
	42, // [42:42] is the sub-list for extension extendee
	0,  // [0:42] is the sub-list for field type_name
}

func init() { file_event_proto_init() }
func file_event_proto_init() {
	if File_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_event_proto_goTypes,
		DependencyIndexes: file_event_proto_depIdxs,
		EnumInfos:         file_event_proto_enumTypes,
		MessageInfos:      file_event_proto_msgTypes,
	}.Build()
	File_event_proto = out.File
	file_event_proto_goTypes = nil
	file_event_proto_depIdxs = nil
}
